### PR TITLE
Silence spurious exception on missing node object in cluster_def

### LINKED ISSUE #1157: nil:NilClass seen in wait_for_hosts.rb
Seeing the following while `wait_for_hosts.rb` is running on current master. Will try to edit this comment with better debug information as soon as possible.

```
Searching for installed hosts, attempt 1/120
undefined method `[]' for nil:NilClass
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:135:in `fetch_cluster_def_http'
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:123:in `fetch_cluster_def'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:137:in `listening_hosts'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:155:in `block in <top (required)>'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `each'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/chefdk/embedded/bin/bundle:22:in `load'
/opt/chefdk/embedded/bin/bundle:22:in `<main>'
	Booted hosts from apache log (3/3):
		10.0.100.11: stage-3
		10.0.100.12: stage-3
		10.0.100.13: stage-3

	Completed installations from apache log (0/3):
		

	Installed hosts that are listening for SSH on port 22 (0/3):
		

	Hosts still missing (3/3):
		bcpc-vm1, bcpc-vm2, bcpc-vm3
```

### PR DESCRIPTION
**Pull request by http-418**
This should fix #1157 by containing the exception to the http method.   Failure to retrieve an http cluster def is marked by returning nil.

### CODE REVIEW

File: lib/cluster-def-gem/lib/cluster_def.rb [hunk 1]
```diff
@@ -118,26 +118,35 @@ def fetch_cluster_def
...
+          response = Faraday.new(proxy: '').get cluster_def_url
+
+          if response.success? then
+            parse_cluster_def(response.body.split("\n"))
+          else
+            nil
+          end
+        rescue Exception => http_e
+          puts http_e
+          puts http_e.backtrace
```
Comment (aespinosa) [inline lib/cluster-def-gem/lib/cluster_def.rb]: Can we print here some form of "it's fine, will fall back" or something?

Comment (http-418) [reply lib/cluster-def-gem/lib/cluster_def.rb]: Added a warning when it falls back.
